# Generated by Django 4.2.2 on 2023-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='pics')),
                ('des1', models.TextField()),
            ],
        ),
    ]
